/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.6/userguide/building_java_projects.html
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.7.10"

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation("com.meilisearch.sdk:meilisearch-java:0.7.2")
    implementation("org.springframework.data:spring-data-commons:3.0.1")

    // Use the Kotlin JUnit 5 integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")

    // Use the JUnit 5 integration.
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.9.1")

    testImplementation("org.springframework:spring-test:6.0.4")
    testImplementation("com.google.guava:guava:31.1-jre")
    testImplementation("org.testcontainers:testcontainers:1.17.6") // Not yet used, but planned for the future
    testImplementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.14.2")
    testImplementation("com.fasterxml.jackson.core:jackson-core:2.14.2")
    testImplementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.14.2")

}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
